import type { Metadata } from "next";
import "./globals.css";
import { AppKontextProvider } from "@/components/kontext-provider";

export const metadata: Metadata = {
  title: "assistant-ui Starter App",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppKontextProvider>
          {children}
        </AppKontextProvider>
      </body>
    </html>
  );
}
